title: Taller3
description: _
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

site:
  name: Taller3
  description: Taller 3 de Software 2
  version: 1.0.0

pages:
  - path: /
    title: Página principal
    source: docs/index.md
    permalink: /

    - path: /test
    title: Página principal
    source: docs/index.md
    permalink: /
